### ISSUE TITLE
Interface support

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-nameof#1]
It would be good to support interfaces. This would mean that the person would have to use this library on the typescript before compiling (shouldn't be done on the original source files obviously).

So maybe this:

```typescript
interface MyInterface {
    prop: string;
}

nameof<MyInterface>();
```

Compiles to:

```javascript
"MyInterface";
```

**Comment by dsherret** [comment]
This is done, but I need to add some documentation for it.

**Comment by styfle** [comment]
@dsherret If you run ts-nameof before ts-compile, does that mean ts-nameof has some safety checks to make sure you didn't do `nameof(undefinedvariablename)`?

**Comment by dsherret** [comment]
@styfle that's a very good point. I've thought about it a lot the past few days. Previously I was using the ts compiler so I could figure that out if the user were to pass in their compiler options to this library as well; however, I decided to drop using the ts compiler for performance reasons and to better support streams (coming this weekend probably).

So yes, you're right that there won't be a safety check when running this on typescript code; however, I would think that the vast majority of people will be using IDEs and the IDE will show them the compiler error when they do `nameof(undefinedvariablename)`. It's not perfect, but they will get the error from their IDE. It's still a lot better than just using strings.

**Comment by dsherret** [comment]
This is in the readme file now.

**Comment by Brandejs** [comment]
HI, 

Im trying your library with angular 2, and i have a problem with `nameof<MyInterface>();`

When i write `nameof<MyInterface>(p => p.prop);` everything is fine. But when i just write `nameof<MyInterface>();` i got an error _"Error: [ts-nameof]: Could not resolve string from expression: nameof()"_

Do you have any suggestion?
Here is link to my repo https://github.com/Brandejs/ng2-nameof-test.

**Comment by dsherret** [comment]
@Brandejs try using the new webpack instructions and don't use tsnameof-loader: https://github.com/dsherret/ts-nameof/blob/master/setup/webpack.md

Also, highly recommend opening new issues in the issue tracker for problems. It's very easy for comments to get lost.
