### ISSUE TITLE
nameof.interpolate not working in ts-nameof.macro

### ISSUE THREAD

**Issue by foresightyj** [dsherret/ts-nameof#104]
I created a minimal project illustrating this bug here https://github.com/foresightyj/nameof-minimal. Just run `npm run build`.

Input:

```
const i = 1;
console.log(nameof.full(m.Data[i].Title));
console.log(nameof.full(m.Data[nameof.interpolate(i)].Title));
```

Output:

```
var i = 1;
console.log("m.Data[.i].Title");
console.log("".concat(i));
```

So I get only the index not the full string. Did I miss anything? Thanks.

I also tried `babel-plugin-ts-nameof` which yields the same result.

**Comment by dsherret** [comment]
Awesome! Thanks so much for the repo as I wasn't able to reproduce this in my test suite, but I investigated it and found the problem. I'll have a fix soon.

**Comment by dsherret** [comment]
@foresightyj ok, if you upgrade to the latest version it should be fixed now. Thanks so much for taking the time to report this and I'm happy you are using the interpolate function 🙂

**Comment by foresightyj** [comment]
Yes. It's working now. Thanks a lot for the quick fix, and also thanks a lot for this awesome library!
