### ISSUE TITLE
Runtime error with ttsc but no idea why

### ISSUE THREAD

**Issue by jasonkuhrt** [dsherret/ts-nameof#114]
In my TS template project repo I am trying to get `nameof` working but it doesn't work. I'm not sure what I'm doing wrong.

The attempt at getting it to work can be found here, its not complicated:

https://github.com/jasonkuhrt/template-typescript-lib/pull/24

Given how simple the setup is, and instructions are, I am wondering if there is a bug in `ts-nameof` 🤔.

**Comment by dsherret** [comment]
@jasonkuhrt I think “plugins” just needs to go under “compilerOptions” and it should work. See https://github.com/cevek/ttypescript#tsconfigjson

**Comment by jasonkuhrt** [comment]
🤦 I just came back to write that

Thanks! haha

**Comment by dsherret** [comment]
No problem! I had no idea what was wrong there for a minute as well 😄
