### ISSUE TITLE
Move to using the transformation api

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-nameof#13]
As title.

Edit (5 May 2017): This change will be made to ts-nameof once the TypeScript compiler easily supports injecting transformations. See [this issue](https://github.com/Microsoft/TypeScript/issues/14419) and upvote it if you support the idea.

**Comment by stephenlautier** [comment]
this is awesome.. looking forward for it :+1:

**Comment by dsherret** [comment]
@stephenlautier I have a simple example working [here](https://github.com/dsherret/ts-nameof/blob/transformationApi/src/main.ts), but I probably won't continue progress on it until something like [this](https://github.com/Microsoft/TypeScript/issues/14654) is agreed to be implemented in TypeScript. I can't think of any other simple way for people to use it otherwise. It doesn't seem very practical for people to pull out the compiler api themselves to use custom transformations for the sake of having nameof :(

It would be a better solution than the current for sure though.

**Comment by stephenlautier** [comment]
agreed, it should be like plugin emitters, similar to how babel works I guess

**Comment by KavanShaban** [comment]
Any update on this, just curious what the API usage and how the TSC compilier picks up the plugin.

**Comment by dsherret** [comment]
@KavanShaban if someone were to use the transformation api as it exists today, they would have to compile their application using the compiler api... that's not ideal for the reasons outlined in [this comment](https://github.com/Microsoft/TypeScript/issues/14419#issuecomment-283722238). It's a huge pain to use.

Once the TypeScript compiler supports a way of doing this beyond the current transformation api, then it will be quick to implement this (max a few days).

**Comment by dsherret** [comment]
I've added support for the typescript transformation API by using [ttypescript](https://github.com/cevek/ttypescript).

This is now available in 1.0.0. Instructions for setup are here: https://github.com/dsherret/ts-nameof/blob/master/setup/transformation-api.md
