### ISSUE TITLE
Config instruction for webpack

### ISSUE THREAD

**Issue by Kukks** [dsherret/ts-nameof#14]
I'm migrating my Aurelia project to webpack and am unsure of how to hook this plugin in with 'awesome-typescript-loader'. Do you have any clues?

**Comment by Kukks** [comment]
Created a simple webpack  loader that uses the replaceInText func. Perhaps you should expose it in main as well?
https://www.npmjs.com/package/ts-nameof-loader

**Comment by dsherret** [comment]
Hey @Kukks, sorry for the long reply. That's awesome! I exposed `replaceInText`. It's available now in v0.9.0. If you update `ts-nameof-loader` to use `ts-nameof` 0.9.0, I'll add a link to it in the readme here if that's alright.

**Comment by Kukks** [comment]
Go for it! :) I bumped up the version and used the exposed replaceInText func just now. @dsherret

**Comment by dsherret** [comment]
I'm just going to reopen this to remind myself to update the readme soon.

**Comment by dsherret** [comment]
Done. Updated the readme in 0.9.1 to include a link to ts-nameof-loader. Thanks a lot man!

**Comment by dsherret** [comment]
Note that `ts-loader` and `awesome-typescript-loader` now both support passing in custom transformers so the `ts-nameof-loader` plugin should no longer be required.

The following instructions should work now:

https://github.com/dsherret/ts-nameof/blob/master/setup/webpack.md

cc @Kukks
