### ISSUE TITLE
nameof with arrays

### ISSUE THREAD

**Issue by intnovaction** [dsherret/ts-nameof#16]
Hello!

I'm using ts-nameof of in conjuction with lodash _.set function to strongly type object paths in reactJS.
I don't know if this an error or a misuse of the package by me:

When I try to make something like this:

```
     var elem = {
            value: "Val",
            items: [
                {
                    prop1: 1,
                    prop2: "pepe"
                }]
        }

        console.log(nameof(elem.items[0].prop1));
```

I get this error:

```
Module build failed: Error: Invalid character in nameof argument: [ -- if this should be a valid character then please log an issue. If you wish, you can manually edit config.js in this package to allow the character.
    at throwInvalidCharacterInArg (D:\Documenta2\TLaw.Docu2\src\TLaw.Docu2.PublicWeb\node_modules\ts-nameof\dist\handleNameOf.js:155:11)
    at tryGetArgs (D:\Documenta2\TLaw.Docu2\src\TLaw.Docu2.PublicWeb\node_modules\ts-nameof\dist\handleNameOf.js:118:24)
    at Object.handleNameOf (D:\Documenta2\TLaw.Docu2\src\TLaw.Docu2.PublicWeb\node_modules\ts-nameof\dist\handleNameOf.js:18:21)
    at NameOfFinder.indexOfAll (D:\Documenta2\TLaw.Docu2\src\TLaw.Docu2.PublicWeb\node_modules\ts-nameof\dist\NameOfFinder.js:20:53)
    at Function.replaceInText (D:\Documenta2\TLaw.Docu2\src\TLaw.Docu2.PublicWeb\node_modules\ts-nameof\dist\replaceInText.js:8:26)
    at Object.module.exports (D:\Documenta2\TLaw.Docu2\src\TLaw.Docu2.PublicWeb\node_modules\ts-nameof-loader\main.js:3:26)
```

I'm trying to get "elem.items[0].prop1".

Any idea? **THANKS**

**Comment by dsherret** [comment]
This is just a scenario I didn't consider. The output of that should be `"prop1"`.

Perhaps `nameof.full(elem.items[0].prop1);` should output `"elem.items[0].prop1"`.

You can temporarily fix this by opening up `node_modules/ts-nameof/dist/config.js` and changing `validCharsInParens` to use `/[A-Za-z0-9_\.\s\t\(\)!,=>;\{\}\-\[\]]/` then use `nameof.full`. I'm going to think about this a bit more and then make a change sometime soon.

**Comment by dsherret** [comment]
@intnovaction couldn't think of a reason not to do this. This is released in 0.9.2. I increased the minor revision only because this is a very minor change with no api changes.

So yeah, just upgrade and use `nameof.full(elem.items[0].prop1);` and it should work well for you. Let me know if you have any other issues or find any problems and I'll take a look into it.

**Comment by intnovaction** [comment]
Hi again, 

I have found another related problem when you use a variable as an iterator.

Here is an example (based on the previous one):
var elem = {
            value: "Val",
            items: [ {1, prop2: "pepe"}]
        }
var index = 0;
console.log(nameof(elem.items[index].prop1));

The output is: "elem.items[index].prop1"
I think that the output should be: "elem.items[**0**].prop1"

I suppose that the expression between the brackets should be eval'd (or something similar).

Any ideas?

Thanks again!

**Comment by dsherret** [comment]
@intnovaction that output seems correct to me. I don't believe nameof should replace any identifiers with their constant values or current value in an iteration. Note that `nameof` is evaluated before the program is run so doing it in an interation wouldn't be possible. I think in this situation you would want to get the string and then add the value into it:

```typescript
console.log(nameof.full(elem.items[index].prop1).replace(nameof(index), index));
// compiles to:
console.log("elem.items[index].prop1".replace("index", index));

// or do (if you're concerned about something else being renamed to "index" and breaking that code)
console.log(`${nameof.full(elem.items)}[${index}].${nameof(elem.items[index].prop1)}`); // could be shortened
```

**Comment by dsherret** [comment]
You may want to follow updates and give feedback in #58.

In the future, the basic idea will be to do:

```ts
console.log(nameof.full(elem.items[nameof.interpolate(index)].prop1));
// transforms to...
console.log(`elem.items[${index}].prop1`);
```
