### ISSUE TITLE
Support an array of names

### ISSUE THREAD

**Issue by tankbob** [dsherret/ts-nameof#18]
Could we have support for an array of values that returns an array.

e.g.

`myProperties: string[] = nameof<Company>(o => o.Name, o => o.Address1, o => o.Address2);`

transpiles to:

`myProperties = ["Name", "Address1", "Address2"];`

Maybe even call it namesOf?

**Comment by dsherret** [comment]
Interesting idea. Perhaps the following?

```typescript
nameof.toArray<Company>(o => [o.Name, o.Address, o.Address2]);
```

Signature:

```typescript
function toArray<T>(func: (obj: T) => any[]): string[];
```

**Comment by tankbob** [comment]
Yes that's much better

**Comment by maleet** [comment]
+1 :)

**Comment by dsherret** [comment]
I'll implement this when I switch this library over to a transformation plugin... I'm still waiting on TypeScript to add support for compiler plugins in tsconfig.json :(

**Comment by Phmager** [comment]
nameof(this.x, this.y, this.a.b.c) would also be nice.
(returns ['x', 'y', 'c'])

**Comment by dsherret** [comment]
This is merged and available now thanks to @cecilyth!

----

One important thing to note is that the following transform is not yet available...

```ts
nameof.toArray<SomeInterface, OtherInterface, SomeType>();
```

... we'll have to wait for TypeScript to support calling functions with a variable number of type arguments (ex. `nameof.toArray<...T>(): string[]`). A workaround would be to just add a bunch of function declarations with different number of type arguments (ex. `nameof.toArray<T1>(): string[]; nameof.toArray<T1, T2>(): string[]; ...etc...`). Might be worth it to do that actually.

Perhaps it would also be good to implement something like `nameof.toArray<T1, T2>((o1, o2) => [o1.test, o2.asdf]);`.

Anyway, something to think about for improving this. Please let me know if you would like any of these features.
