### ISSUE TITLE
import into Angular2

### ISSUE THREAD

**Issue by kstraszewski** [dsherret/ts-nameof#22]
Hey, I was trying to add your library to my angular2 Project, and when i import, by adding /// reference to my app.module.ts I recive this error: Cannot find namespace 'NodeJS', any idea how to use it with angular2?

**Comment by dsherret** [comment]
@kstraszewski you're right! Thanks for opening this issue! I never thought about how this would be a problem for web projects.

This is fixed in 0.10.2. Let me know if you have any problems with that build.
