### ISSUE TITLE
Cannot find name 'nameof'. on Angular2

### ISSUE THREAD

**Issue by kstraszewski** [dsherret/ts-nameof#23]
Hey, i want to implement your library to my angular2 project, so first I download it via npm, then i add 

`/// <reference path="../../node_modules/ts-nameof/ts-nameof.d.ts" />`

to my app.module.ts file and in constructor of my base app.component im using nameof function, Webstorm doesn't find this error, but when i run "ng serve" this apears:

> (14,17): Cannot find name 'nameof'. Did you mean 'name'?

**Comment by dsherret** [comment]
Hey @kstraszewski, I'm not too familiar with `ng serve`, but it seems like ts-nameof is not being run on the files before being passed to the compiler.

Does it have a build configuration? I think it uses web pack? If so, have you tried using https://github.com/Kukks/ts-nameof-loader?

**Comment by kstraszewski** [comment]
Yea, I know that this is a problem, but i have no idea how to implement this loader, that angular-cli would be aware of this lib. There is no such thing as webpack.config.js in angular-cli as default, there is only angular-cli.js and this is the only configuration file for Angular2. Angular-cli is a wrap-up of webpack if I understand it correctly, but i didn't found any way to implement 3th party loaders. Is there any other way to work this around?

**Comment by Kukks** [comment]
Hey @kstraszewski 
From what I've read it seems the angular-cli hide the webpack config to "protect" its users, doh /facepalm.

Here's one solution I found: 
https://stackoverflow.com/questions/39187556/angular-cli-where-is-webpack-config-js-file-new-2017-feb-ng-eject

**Comment by dsherret** [comment]
That's too bad. It seems like ejecting is the only option for now.

Hopefully sometime soon TypeScript will add support for custom transforms specified in tsconfig.json so that this library will become easier to use.
