### ISSUE TITLE
Issues with source-map generation

### ISSUE THREAD

**Issue by csersoft** [dsherret/ts-nameof#27]
In the **Ionic** project. use webpack **ts-nameof-loader**.

When the rule is:
```
      {
        test: /\.ts$/i,
        exclude: /node_modules/,
        loader: "ts-nameof-loader"
      }
```
ts-nameof work normally, but sourcemap abnormal.

When the rule is:
```
      {
        test: /\.ts$/i,
        enforce: "pre",
        exclude: /node_modules/,
        loader: "ts-nameof-loader"
      }
```
ts-nameof not working, but sourcemap normal.

**Comment by dsherret** [comment]
Right now this is listed in the readme as not having support. I'm not familiar with source map files, but if someone else is then it would be appreciated if they could add it to this library.

**Comment by dsherret** [comment]
Note that source map support is available by using the TypeScript transformation API. Instructions are here: https://github.com/dsherret/ts-nameof/blob/master/setup/transformation-api.md

**Comment by dsherret** [comment]
@csersoft this should be fixed with webpack if upgrading to ts-nameof 2 and then following these setup instructions: https://github.com/dsherret/ts-nameof/blob/master/setup/webpack.md

Note: ts-nameof-loader is no longer required.

**Comment by csersoft** [comment]
thanks !
