### ISSUE TITLE
Parser will break if file contains regex with string char

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-nameof#28]
I just thought of this scenario (untested, but I'm pretty sure it won't work):

```ts
const t = /`/g; 

nameof(T); // won't work
```

Basically, the parser needs to be improved to detect when it's within a regular expression literal.

Edit 2018-05-01: This is a very rare scenario to encounter, but I should fix this ASAP.

**Comment by teemuq** [comment]
After updating from 1.0.1 to 1.0.2/1.0.3 we are getting errors from division operations:
``
const t = 2 / 1;
``
Maybe this fix needs some fine-tuning?

**Comment by dsherret** [comment]
Thanks for the heads up @teemuq! I just opened #34. Will be an easy fix and I'll have it done soon.

I just noticed there's now a way to inject custom transformers in webpack. This library is implemented twice... once for working on a string and once for working with the typescript compiler api's custom transformers. If the custom ast transformer is used then the experience using this library will be much more reliable because it is working with typescript's parsed ast rather than relying on my own stupid/fast parser. I'll update the docs with that soon as well so that you can take advantage of that method and not run into this trouble again.

**Comment by dsherret** [comment]
@teemuq this is fixed now in version 2.0. I recommend upgrading and then following these instructions for setup with webpack: https://github.com/dsherret/ts-nameof/blob/master/setup/webpack.md

This setup will be much more reliable because it's going through the transformation api.

**Comment by teemuq** [comment]
Thank you @dsherret! I tested the 2.0 with the new config and it works like a charm. Good job!
