### ISSUE TITLE
FuseBox plugin

### ISSUE THREAD

**Issue by samppis** [dsherret/ts-nameof#29]
I've created a plugin to use ts-nameof with [FuseBox](https://fuse-box.org/), in case you want to list that in the readme: https://github.com/samppis/ts-nameof-fusebox-plugin

**Comment by dsherret** [comment]
@samppis That is awesome! Thanks so much! I've added it to the readme.

I wish tsconfig.json would have configurable transformations so this could easily work in any build environment.

**Comment by dsherret** [comment]
@samppis I believe the plugin is no longer necessary. It seems fusebox supports passing in a `ts.TransformerFactory<ts.SourceFile>` now. I tested it out and it should work with the following setup:

https://github.com/dsherret/ts-nameof/blob/master/setup/fusebox.md
