### ISSUE TITLE
Using ts-nameof with react-native-typescript-transformer

### ISSUE THREAD

**Issue by wh1t3cAt1k** [dsherret/ts-nameof#30]
I am wondering if it is possible to use `ts-nameof` in a React Native project that already uses [react-native-typescript-transformer](https://github.com/ds300/react-native-typescript-transformer).

The setup section of the library prescribes using the TS transformation API with `ttsc` compilation.

My understanding is that it won't work seamlessly with RN TS transformer.

Could anyone advise other options?

**Comment by dsherret** [comment]
I'm going to take a guess here... no clue if this will work and probably won't, but could you try this out?

1. Install `ttypescript` and `ts-nameof`:
    ```
    npm install --save-dev ttypescript ts-nameof
    // or
    yarn add --dev ttypescript ts-nameof
    ```

2. Add `ts-nameof` to `tsconfig.json` as a custom transformer:

    ```
    {
        "compilerOptions": {
            "plugins": [{ "transform": "ts-nameof", "type": "raw" }]
        }
    }
    ```

3. In `rn-cli.config.js` mentioned at https://github.com/ds300/react-native-typescript-transformer, add an import for "ttypescript".

    ```ts
    var ttypescript = require("ttypescript");
    ```

I believe importing `ttypescript` will currently cause the typescript module to be patched with ttypescript's modifications. If not, I'll open an issue at ttypescript to see if there's a way to patch an existing typescript version.

---

Also, doesn't look like there's a way to use a custom typescript version with RN TS transformer. It would probably be best if that allowed providing a custom version of the compiler.

**Comment by wh1t3cAt1k** [comment]
Hi David,

Hey, don't apologize for troubles that you didn't create! 😃 

Unfortunately the approach didn't work:

![image](https://user-images.githubusercontent.com/5159662/42501871-4d36db04-843d-11e8-9488-a09262104150.png)

For reference, here is my `rn-cli.config.js`:

```
var ttypescript = require("ttypescript");

module.exports = {
    getTransformModulePath() {
      return require.resolve("react-native-typescript-transformer");
    },
    getSourceExts() {
      return ["ts", "tsx"];
    }
};
```

**Comment by wh1t3cAt1k** [comment]
**WORKAROUND**:

I am currently using the following workaround:

```
// modules/nameof.ts
// -
export const nameof = (variableObject: any) => Object.keys(variableObject)[0];
```

But the downside is that I have to use the object syntax and redundantly pass objects around:

```
import { nameof } from 'modules/nameof`

const variable = 5;
const name = nameof({ variable});
```

Moreover, it is not possible to obtain the name of a nested property without destructuring:

```
import { nameof } from 'modules/nameof';

const foo = { bar: 5 };

// Won't work: 
// const name = nameof({ foo.bar });

// I have to explicitly destructure:
// -
const { bar } = foo;
const name = nameof({ bar });
```

All in all, @dsherret I would be glad if we could get your package to work in react-native. Is there anything else I can help with?

**Comment by dsherret** [comment]
Sorry, I have completely neglected responding to this.

That's a pretty good idea for a workaround! For a property, you may want to do this:

```ts
function nameofProp<T>(obj: T, name: keyof T) {
    return name;
}

const myObj = { prop: "" };
const result = nameofProp(myObj, "prop");
```

The only way I can see this being fixed is if [react-native-typescript-transformer](https://github.com/ds300/react-native-typescript-transformer) is changed to allow passing in a custom version of the compiler. For example, [ts-node](https://github.com/TypeStrong/ts-node) allows specifying a different typescript compiler to use by specifying that as a command line option or environment variable (most likely an environment variable would by best for your situation).

**Comment by wh1t3cAt1k** [comment]
@dsherret hi David, is there any new hope with the 2.0 version?

**Comment by dsherret** [comment]
@wh1t3cAt1k no, still not possible. I've opened https://github.com/ds300/react-native-typescript-transformer/issues/88

By the way, it would be pretty easy to fork that project then inject ts-nameof on [this line](https://github.com/ds300/react-native-typescript-transformer/blob/7aa16d351a14068b1dcfa95aa99edaa163686700/index.js#L210) and provide the `customTransformers` option (ex. `customTransformers: { before: [tsNameof] }`).

**Comment by dsherret** [comment]
See my comment here about babel supporting typescript: https://github.com/dsherret/ts-nameof/issues/37#issuecomment-443548609

**Comment by dsherret** [comment]
Considering https://github.com/dsherret/ts-nameof/tree/master/packages/babel-plugin-ts-nameof now exists, I suggest using `@babel/preset-typescript`.
