### ISSUE TITLE
Allow $ in nameof

### ISSUE THREAD

**Issue by Kukks** [dsherret/ts-nameof#32]
VueJs utilizes a $ on some reserved view model keywords and using nameof with them causes the following error:

`Error: Invalid character in nameof argument: $ -- if this should be a valid character then please log an issue. If you wish, you can manually edit config.js in this package to allow the character.`

I'm thinking it should be globally allowed from the plugin itself

**Comment by dsherret** [comment]
Done. Thanks for reporting and I'm surprised I missed this.

Released in 1.0.1.
