### ISSUE TITLE
Support custom path signature

### ISSUE THREAD

**Issue by eliottrobson** [dsherret/ts-nameof#42]
I appreciate that the current output matches the code expectation:

`nameof.full<IState>(state => state.a.b.c);` becomes `a.b.c`. But I think sometimes that the path signature might need to be different.

For this it would be good to do:

`nameof.full<IState>(state => state.a.b.c, "/");` (or similar) which would compile to `a/b/c`

I suppose it would be possible to apply a simple string replace, but just curious if it would be something for the core?

**Comment by dsherret** [comment]
Good idea, but I'm wondering how someone would provide both a separator and period index. For example `nameof.full<IState>(state => state.a.b.c, 1, "/");` -> `b/c` might work, but it's meaning is a bit obscured.

Perhaps #21 would make this a little easier?

```ts
nameof.split<IState>(state => state.a.b.c).join("/");
```

**Comment by eliottrobson** [comment]
I suppose the best option would be to have an overload to enable either the index or the seperator or both (index then seperator). Should be type hintable using string and number.

However, the split and join is a viable workaround!

**Comment by dsherret** [comment]
Split is implemented now, so recommend using that in this scenario. I updated the docs.
