### ISSUE TITLE
Use with Jest

### ISSUE THREAD

**Issue by lonix1** [dsherret/ts-nameof#45]
I followed [the instructions](https://github.com/dsherret/ts-nameof/blob/HEAD/setup/jest.md) for integrating with Jest. It works.

However I got a warning:

> ts-jest[main] (WARN) Replace any occurrences of "ts-jest/dist/preprocessor.js" or  "<rootDir>/node_modules/ts-jest/preprocessor.js" in the 'transform' section of your Jest config with just "ts-jest".

So I did that, but it doesn't work:
````json
transform: {
  "^.+\\.ts$": "ts-jest"
}
````

I also tried [something I found](https://kulshekhar.github.io/ts-jest/user/config/compiler) at ts-jest, but it doesn't work:
````json
globals: {
  "ts-jest": {
    "compiler": "ttypescript"
  }
}
````

The warning implies it's possible - with some tweaking we could avoid the preprocessor and increase speed.

Has anyone got this to work?

cc @dsherret, @Kukks

**Comment by dsherret** [comment]
Oh interesting! I did not know you can include a custom compiler with ts-jest. Did you try these steps?

1. Run `npm install --save-dev ttypescript ts-nameof`
2. Update `jest.config.js` or `package.json` to:
    ```
    "ts-jest": {
      "compiler": "ttypescript"
    }
    ```
3. Update `tsconfig.json` to:
    ```
    {
      "compilerOptions": {
        "plugins": [{ "transform": "ts-nameof", "type": "raw" }]
      }
    }
    ```

(I would try it out myself, but I'm busy at the moment... I'll try later though)

**Comment by lonix1** [comment]
Nope that's exactly what I tried, doesn't work for me. :(

**Comment by lonix1** [comment]
With the new typings you just released is it now possible to remove "preprocessor" in favor of "ts-jest"?

I did that and it didn't work (complained about not knowing what `nameof` is during testing), but maybe that's because there is some config step I don't know about?

**Comment by dsherret** [comment]
@lonix1 no, that's solely for type checking and doesn't affect the emit.

I just did a new release with ts-nameof@3.0.0 that should support ts-jest using a compiler transformation... I spent some time reading the ts-jest source code and came up with a hacky workaround.

Please read the instructions here and let me know if it works: https://github.com/dsherret/ts-nameof/blob/master/packages/ts-nameof/setup/jest.md

**Comment by lonix1** [comment]
I get `[ts-nameof]: Unhandled node kind (212) in text: value as number (Please open an issue if you believe this should be supported.)`

.jest.config.js
````javascript
module.exports = {
  testEnvironment: "node",
  preset: "ts-jest",
  setupTestFrameworkScriptFile: "jest-extended",
  testMatch: [ "**/test/**/*.test.(ts|js)" ],
  transform: { "^.+\\.ts$": "<rootDir>/.jest.tspreprocessor.js" },
  globals: {
    "ts-jest": { "astTransformers": ["ts-nameof"] }
  }
}
````

I'm obviously doing something really silly, so lets wait for someone else to complain before we assume it's the new code. I'm really appreciative for this library - having extra declarations in each file is a small price to pay for the benefit of having `nameof()` support!

**Comment by dsherret** [comment]
No, I just made a major change in 3.0.0 to support babel and didn't handle type assertions. What does the full nameof call expression look like that has `value as number`?

**Comment by dsherret** [comment]
@lonix1 ok, sorry about that! Should be fixed now in 3.0.1.

**Comment by lonix1** [comment]
Strange now it tells me again `ts-jest[main] (WARN) Replace any occurrences of "ts-jest/dist/preprocessor.js" or  "<rootDir>/node_modules/ts-jest/preprocessor.js" in the 'transform' section of your Jest config with just "ts-jest".`

But stranger is that I just get a standard stacktrace, it doesn't tell me where in my code the problem occurred. 

````
  ● Test suite failed to run

    [ts-nameof]: Unhandled node kind (212) in text: value as number (Please open an issue if you believe this should be supported.)

      at Object.throwError (node_modules/ts-nameof/dist/external/transforms-ts/external/common/errors.js:4:11)
      at parseCommonNode (node_modules/ts-nameof/dist/external/transforms-ts/parse.js:63:25)
      at node_modules/ts-nameof/dist/external/transforms-ts/parse.js:36:63
          at Array.map (<anonymous>)
      at parseArguments (node_modules/ts-nameof/dist/external/transforms-ts/parse.js:36:35)
      at parseNameof (node_modules/ts-nameof/dist/external/transforms-ts/parse.js:21:24)
      at Object.parse (node_modules/ts-nameof/dist/external/transforms-ts/parse.js:16:36)
      at Object.visitNode (node_modules/ts-nameof/dist/external/transforms-ts/transformerFactory.js:28:31)
      at visitNodeAndChildren (node_modules/ts-nameof/dist/text/replaceInText.js:44:46)
      at node_modules/ts-nameof/dist/text/replaceInText.js:43:74
````

**Comment by dsherret** [comment]
I think you need to change `transform: { "^.+\\.ts$": "<rootDir>/.jest.tspreprocessor.js" },` to `transform: { "^.+\\.tsx?$": "ts-jest" }`.

The `value as number` issue should be fixed in ts-nameof 3.0.1 (just released).

**Comment by dsherret** [comment]
Side note: I just opened #47.

**Comment by lonix1** [comment]
Okay! 3.0.1 makes those errors go away, which means now I get nameof support without littering all my files with references! :+1: 

But I still need to use that "preprocessor" despite the warning, otherwise I get: `ReferenceError: nameof is not defined`. I guess that has nothing to do with this package, and is related to ts-jest itself?

**Comment by dsherret** [comment]
Hmmm strange. Are you using the latest ts-jest?

**Comment by lonix1** [comment]
Yeah. Actually it says `ts-jest[versions] (WARN) Version 24.0.0 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=22.0.0 <24.0.0). Please do not report issues in ts-jest if you are using unsupported versions.`

But regardless both the latest and latest-1 versions give that same warning.

I don't mind that preprocessor, everything works for me now. Maybe we can revisit once more users install the new bits. Maybe it's just me after all. Should I close the issue?

**Comment by lonix1** [comment]
BTW for everything to work for me, I don't need to enable "astTransformers", it works regardless.

**Comment by lonix1** [comment]
Yeah I'm using 23.10.5 too. So must be a local problem - I'm gonna close this issue, I think you've solved the most important stuff. If anyone else complains about warnings/speed we can look into it again... Thanks again!

(BTW the best idea is to have a sample app, which just means basic configuration files, one test file, and nothing else. I'll try put something together, but then again it doesn't work for me for some reason. If I can get something like that working, I'll post here.)

**Comment by lonix1** [comment]
For anyone else stumbling on this: when I don't use the preprocessor I get `"nameof is not defined"`. If you have the same problem, add your config here and let's get to the bottom of this.

**Comment by lonix1** [comment]
Hey @dsherret I just upgraded to today's `"ts-jest": "24.0.0"`.

I was still getting those warnings, but since it's a new version I wanted to see if the problem is still there. So in `jest.config` I replaced

````
transform: {
    "^.+\\.ts$": "<rootDir>/.jest.tspreprocessor.js"
}
````

with

````
transform: {
    "^.+\\.ts$": "ts-jest"
}
````
And now the warnings go away, and the tests seem to work! So the issue is finally resolved. And no need for that preprocessor any more, so presumably the tests will be faster (though I haven't felt a speed difference, but maybe that's just me).

**Comment by dsherret** [comment]
@lonix1 cool, I'm glad it's working for you now :)

The tests should be faster because it's not parsing the file twice, but parsing is actually pretty fast so yeah it might not be noticeable.

**Comment by lonix1** [comment]
I can't believe all the hoops I had to jump through to get this working properly, and yet, I'm HAPPY to have done so.

All for a **single operator**! Says a lot. So sorely missing from the language itself!

Kudos again for this library, what a difference it makes to my code!
