### ISSUE TITLE
[Question] Use nameof inside decorator

### ISSUE THREAD

**Issue by lonix1** [dsherret/ts-nameof#48]
I'm using the inversify IOC container.

This is used in controllers' action methods:

````
@httpGet("/:id")
public async getUser(@requestParam("id") id: number): Promise<User> {     // <----- "id"
  // ...
}
````

None of these things are available in that context: `this`, `arguments`, `id`.

Is there some trick to avoid that `"id"` magic string in the argument list?

---
A workaround:

````typescript
const names = {
  getUser: {
    id: "id"
  }
};
````
And then: `nameof(names.getUser.id)`. But that's not ideal.

**Comment by dsherret** [comment]
There's not any way to access a parameter's name outside the body of the function/method.

You may just want to not use `nameof` at all here since the parameter name doesn't need to match what's in `requestParam`'s argument?

```ts
const names = {
    id: "id"
};

// etc...

@httpGet(`/:${names.id}`)
public async getUser(@requestParam(names.id) id: number): Promise<User> {
  // ...
}
```

**Comment by lonix1** [comment]
Yeah that's what I'm doing, but I was hoping there was some compile-time magic we could use.

It's really unfortunate that ts doesn't allow **macros** like in c/c++, or a cross between macros and asts. Then this sort of stuff would be easy. But it's like you said, the language itself doesn't expose the parameter itself. It's strange that for a dynamic language that sort of thing can't be hacked at compile-time.

However - that would be easy enough if the language had reflection like c#/java. Are you aware of any packages for node/ts that do that sort of thing? I looked at [reflect-metadata](https://www.npmjs.com/package/reflect-metadata) which seems to be the most used in this field, but it isn't really reflection/introspection it's just annotation and then reading back those annotations.

**Comment by dsherret** [comment]
One possibility is to create a linting rule to ensure `@requestParam("id")` matches the string in `@httpGet("/:id")`. The downside is rename refactors won't work, but maybe that's not a big deal?

Yeah, `reflect-metadata` is the closest thing to reflection in c#/java, but as you mentioned, that just stores information at compile time to overcome that shortcoming at runtime. My other library [ts-morph](https://github.com/dsherret/ts-morph) is useful for working with the ast.

What would your ideal code look like?

By the way, another possibility would be to create a compiler transform that automatically inserts `@requestParam("id")` decorators to the parameters based on the names specified in the string. Then you could also throw if there's a mismatch.

**Comment by lonix1** [comment]
Thanks for telling me about `ts-morph`, it looks really cool!

Your idea of a compiler transform is really interesting, I'm going to play around with that and see if I can come up with something. In .net there is something "similar" (t4 templates) which are basically design-time code generators (code that generates code). Maybe that's something I'll look into.

I know I sound like every other newcomer to node, but... I really miss net/java's reflection... especially in testing!

Thanks for all the tips. If I come up with something I'll post back here!

**Comment by dsherret** [comment]
@lonix1 I think ideally the library itself should be using reflect-metadata and then it should make the parameters default to implicitly have `@requestParam("parameterNameGoesHere")`. You may want to open an issue in their project and ask them if that's possible.

I miss reflection too. I spend most of my time in c# code.
