### ISSUE TITLE
Name of the file that generates the error.

### ISSUE THREAD

**Issue by parloti** [dsherret/ts-nameof#84]
https://github.com/dsherret/ts-nameof/blob/1a648547d6ccf15990782123d25c25d88232ea4c/packages/transforms-ts/src/parse.ts#L93

I think it would be interesting to also have the file name (sourceFile.fileName) in this message.

Because the current message does not help and find the error.
Current Message: "Unhandled node kind (99) in text: null (Please open an issue if you believe this should be supported.)"

**Comment by dsherret** [comment]
Definitely! This is #47.
