### ISSUE TITLE
Publish declaration file as @types package

### ISSUE THREAD

**Issue by CoenraadS** [dsherret/ts-nameof#9]
Hello

This is a great project. Have you considered publishing the declaration file?

**Comment by dsherret** [comment]
Hi @CoenraadS, right now the declaration file is just living in npm and you just have to reference it in a single .d.ts file in your project by doing (with the correct relative path):

```typescript
/// <reference path="node_modules/ts-nameof/ts-nameof.d.ts" />
```

Can you think of a better way? Where would you suggest I publish it to?

**Comment by CoenraadS** [comment]
I meant to DefinitelyTyped. I know its not much work to manually reference it though. Great project 👍

**Comment by Kukks** [comment]
Referencing it manually doesn't always work for me.

For reference, I used this: 
`typings install file:node_modules/ts-nameof/ts-nameof.d.ts --save --global`

Great project btw!

**Comment by dsherret** [comment]
`@types/ts-nameof` is now published. I will update the instructions soon.

```ts
npm install @types/ts-nameof --save-dev
```
